### ISSUE TITLE
smc++ split time

### ISSUE THREAD

**Issue by zhidaobuzhidao** [mishaploid/carrot-demography#1]
Hi,
  I really want to learn how to calculate the split time of two groups in your article fig3d? 
  Could you tell me which command I can get a series of split times after using smc++ to plot fig3d?
  Looking forward to your reply!
![image](https://github.com/user-attachments/assets/b919008e-c711-405a-8e64-845778ed568e)

**Comment by mishaploid** [comment]
Hello! Thanks for this question, it prompted me to properly update this git repo and add more information on the analysis and results for this project. I've added a [markdown file](https://github.com/mishaploid/carrot-demography/blob/70db1db0c94c37a371cac46773e0c05a56c491f8/summarize_smc_results.md) that walks through calculating split times from smc++ results and creating a plot with the bootstrapped and point estimates of divergence time. 

General steps required to create a similar plot: 
* Obtain marginal estimates of population size history for each population using [smcpp estimate](https://github.com/popgenmethods/smcpp?tab=readme-ov-file#estimate) or [smcpp cv](https://github.com/popgenmethods/smcpp?tab=readme-ov-file#cv)
  - To assess uncertainty, also run this on a set of parametric bootstraps for each population; these can be generated by chunking up the genome and resampling (I used 10 bootstrap replicates per population)  
* Fit a clean split model using [smcpp split](https://github.com/popgenmethods/smcpp?tab=readme-ov-file#split) to estimate joint demography for population pairs 
* Each split model output will have a `model.final.json` file that will contain values for `N0` and `split`, you can use these values to convert from coalescent scaling to generations by multiplying `2 * N0 * split`. Carrot has a generation time of two years, so I multiplied by two to get the time in years: `2 * N0 * split * 2`. See discussion [here](https://github.com/popgenmethods/smcpp/issues/10) for more context.
